# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven, Docker, and ECS

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build jar with Maven using Docker profile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: wtvamp
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
      uses: actions/setup-java@v2
      with:
        # https://github.com/actions/setup-java#supported-distributions
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    -
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    -
      name: Java Build
      id: java_build
      run: |-
        mvn -B clean package --file pom.xml -P docker
    -
      name: Docker Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wtvamp/pokemonwebgame:beta
